# Generated by Django 5.2.1 on 2025-06-11 18:41

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('business_name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=30)),
                ('whatsapp_number', models.CharField(max_length=30)),
                ('instagram_handle', models.CharField(blank=True, max_length=30)),
                ('facebook_handle', models.CharField(blank=True, max_length=30)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='users/profile_photos/')),
                ('bio', models.TextField(blank=True)),
                ('x_handle', models.CharField(blank=True, max_length=30)),
                ('linkedin_handle', models.CharField(blank=True, max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BusinessCertificateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=100)),
                ('place_of_birth', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('contact_number_one', models.CharField(max_length=15)),
                ('contact_number_two', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('business_name', models.CharField(max_length=100)),
                ('nature_of_business', models.CharField(max_length=100)),
                ('type_of_business', models.CharField(choices=[('sole_proprietorship', 'Sole Proprietorship'), ('non_governmental_organization', 'Non-Governmental Organization'), ('limited_liability_company', 'Limited Liability Company')], max_length=100)),
                ('postal_address', models.TextField()),
                ('company_email', models.EmailField(max_length=100)),
                ('company_building_number', models.CharField(max_length=10)),
                ('company_landmark', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('company_gps_address', models.CharField(max_length=100)),
                ('ghana_card_number', models.CharField(max_length=100)),
                ('tin_number', models.CharField(max_length=100)),
                ('application_status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('completed_documentation', 'Completed Documentation'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FDAApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_certificate', models.FileField(upload_to='fda/business_certificates/')),
                ('business_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('products', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='fda/logos/')),
                ('lab_results', models.FileField(blank=True, null=True, upload_to='fda/lab_results/')),
                ('product_labels', models.FileField(blank=True, null=True, upload_to='fda/product_labels/')),
                ('food_handler_cert', models.FileField(blank=True, null=True, upload_to='fda/food_handler_certs/')),
                ('process_description', models.TextField(blank=True, null=True)),
                ('voice_note', models.FileField(blank=True, null=True, upload_to='fda/voice_notes/')),
                ('facility_video', models.FileField(blank=True, null=True, upload_to='fda/facility_videos/')),
                ('items_equipment', models.TextField()),
                ('staff_roles', models.TextField()),
                ('application_status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('completed_documentation', 'Completed Documentation'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fda_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Logged In'), ('logout', 'Logged Out'), ('profile_update', 'Profile Updated'), ('message_sent', 'Message Sent'), ('message_received', 'Message Received'), ('submit_product', 'Submitted Product Application'), ('submit_facility', 'Submitted Facility Application'), ('submit_business', 'Submitted Business Certificate Application'), ('status_changed', 'Application Status Updated')], max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
