# Generated by Django 5.2.1 on 2025-06-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='business_name',
            field=models.CharField(max_length=250, verbose_name='Business/Company Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='facebook_handle',
            field=models.CharField(blank=True, max_length=30, verbose_name='Facebook Profile'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=30, verbose_name='Instagram Handle'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='linkedin_handle',
            field=models.CharField(blank=True, max_length=30, verbose_name='LinkedIn Profile'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=30, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile_photos/', verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='whatsapp_number',
            field=models.CharField(max_length=30, verbose_name='Whatsapp Number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='x_handle',
            field=models.CharField(blank=True, max_length=30, verbose_name='X (Formerly Twitter) Handle'),
        ),
    ]
