# Generated by Django 5.2.1 on 2025-06-19 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_bio_alter_customuser_business_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FDAFoodRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_handlers_card', models.CharField(choices=[('have', 'I have this'), ('need_help', 'I need help from PFS')], max_length=10, verbose_name="Food Handler's Card")),
                ('product_lab_test', models.CharField(choices=[('have', 'I have this'), ('need_help', 'I need help from PFS')], max_length=10, verbose_name='Product Lab Test')),
                ('product_label', models.CharField(choices=[('have', 'I have this'), ('need_help', 'I need help from PFS')], max_length=10, verbose_name='Product Label')),
                ('business_certificate', models.CharField(choices=[('have', 'I have this'), ('need_help', 'I need help from PFS')], max_length=10, verbose_name='Business Certificate')),
                ('product_pictures', models.BooleanField(default=False, verbose_name='I have Product Pictures')),
                ('product_samples', models.BooleanField(default=False, verbose_name='I have Product Samples')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fda_food_requirements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
