# Generated by Django 5.2 on 2025-04-24 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_customuser_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FDAApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_certificate', models.FileField(upload_to='fda/business_certificates/')),
                ('business_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('products', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='fda/logos/')),
                ('lab_results', models.FileField(blank=True, null=True, upload_to='fda/lab_results/')),
                ('product_labels', models.FileField(blank=True, null=True, upload_to='fda/product_labels/')),
                ('food_handler_cert', models.FileField(blank=True, null=True, upload_to='fda/food_handler_certs/')),
                ('process_description', models.TextField(blank=True, null=True)),
                ('voice_note', models.FileField(blank=True, null=True, upload_to='fda/voice_notes/')),
                ('facility_video', models.FileField(blank=True, null=True, upload_to='fda/facility_videos/')),
                ('items_equipment', models.TextField()),
                ('staff_roles', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fda_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
