# Generated by Django 5.2.1 on 2025-06-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_fdafoodrequirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fdafoodrequirement',
            name='business_certificate',
            field=models.CharField(choices=[('have', 'I have this'), ('need_help', 'I need help from PFS')], default='', max_length=10, verbose_name='Business Certificate'),
        ),
        migrations.AlterField(
            model_name='fdafoodrequirement',
            name='food_handlers_card',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=10, verbose_name="Food Handler's Card"),
        ),
        migrations.AlterField(
            model_name='fdafoodrequirement',
            name='product_lab_test',
            field=models.CharField(choices=[('have', 'I have this'), ('need_help', 'I need help from PFS')], default='', max_length=10, verbose_name='Product Lab Test'),
        ),
        migrations.AlterField(
            model_name='fdafoodrequirement',
            name='product_label',
            field=models.CharField(choices=[('have', 'I have this'), ('need_help', 'I need help from PFS')], default='', max_length=10, verbose_name='Product Label'),
        ),
        migrations.AlterField(
            model_name='fdafoodrequirement',
            name='product_pictures',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=10, verbose_name='I have Product Pictures'),
        ),
        migrations.AlterField(
            model_name='fdafoodrequirement',
            name='product_samples',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=10, verbose_name='I have Product Samples'),
        ),
    ]
