# Generated by Django 5.2 on 2025-04-25 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_fdaapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='fdaapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='BusinessCertificateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('nature_of_business', models.CharField(max_length=100)),
                ('postal_address', models.TextField()),
                ('contact_number_one', models.CharField(max_length=15)),
                ('contact_number_two', models.CharField(max_length=15)),
                ('company_email', models.CharField(max_length=50)),
                ('company_building_number', models.CharField(max_length=10)),
                ('company_landmark', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('company_gps_address', models.CharField(max_length=100)),
                ('ghana_card_number', models.CharField(max_length=100)),
                ('tin_number', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
