# Generated by Django 5.2.1 on 2025-06-24 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_fdafoodrequirement_business_certificate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FDACosmeticsRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_label', models.CharField(choices=[('have', 'I have this'), ('need_help', 'I need help from PFS')], default='', max_length=10, verbose_name='Product Label')),
                ('business_certificate', models.CharField(choices=[('have', 'I have this'), ('need_help', 'I need help from PFS')], default='', max_length=10, verbose_name='Business Certificate')),
                ('product_pictures', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=10, verbose_name='I have Product Pictures')),
                ('product_samples', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=10, verbose_name='I have Product Samples')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fda_cosmetics_requirements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FDAEateriesRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_handler_card', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=10, verbose_name="Food Handler's Card")),
                ('list_of_recipes', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=10, verbose_name='List of Recipes')),
                ('recipe_preparation_steps', models.CharField(choices=[('have', 'I have this'), ('need_help', 'I need help from PFS')], default='', max_length=10, verbose_name='Recipe Preparation Steps')),
                ('business_certificate', models.CharField(choices=[('have', 'I have this'), ('need_help', 'I need help from PFS')], default='', max_length=10, verbose_name='Business Certificate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fda_eateries_requirements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
