# Generated by Django 5.2 on 2025-04-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_fdaapplication_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fdaapplication',
            name='application_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('completed_documentation', 'Completed Documentation')], default='pending', max_length=50),
        ),
    ]
