# Generated by Django 5.2.1 on 2025-06-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_fdacosmeticsrequirement_fdaeateriesrequirement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fdaeateriesrequirement',
            old_name='food_handler_card',
            new_name='food_handlers_card',
        ),
    ]
