# Generated by Django 5.2 on 2025-05-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_fdaapplication_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscertificateapplication',
            name='application_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('completed_documentation', 'Completed Documentation')], default='pending', max_length=50),
        ),
    ]
