# Generated by Django 5.2.1 on 2025-06-24 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_food_handler_card_fdaeateriesrequirement_food_handlers_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fdaapplication',
            old_name='food_handler_cert',
            new_name='food_handlers_card',
        ),
        migrations.RemoveField(
            model_name='fdaapplication',
            name='facility_video',
        ),
        migrations.RemoveField(
            model_name='fdaapplication',
            name='items_equipment',
        ),
        migrations.RemoveField(
            model_name='fdaapplication',
            name='lab_results',
        ),
        migrations.RemoveField(
            model_name='fdaapplication',
            name='staff_roles',
        ),
        migrations.RemoveField(
            model_name='fdaapplication',
            name='voice_note',
        ),
    ]
