# Generated by Django 5.2 on 2025-05-03 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_businesscertificateapplication_application_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Logged In'), ('logout', 'Logged Out'), ('profile_update', 'Profile Updated'), ('message_sent', 'Message Sent'), ('message_received', 'Message Received'), ('submit_product', 'Submitted Product Application'), ('submit_facility', 'Submitted Facility Application'), ('submit_business', 'Submitted Business Certificate Application'), ('status_changed', 'Application Status Updated')], max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
