# Generated by Django 5.2.1 on 2025-06-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_food_handler_cert_fdaapplication_food_handlers_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fdaapplication',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to='fda/voice_notes/'),
        ),
    ]
