# Generated by Django 5.2 on 2025-05-03 18:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscertificateapplication',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesscertificateapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
