# Generated by Django 5.2.1 on 2025-05-15 04:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_businesscertificateapplication_submitted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscertificateapplication',
            name='dob',
            field=models.DateField(default='1990-04-05'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesscertificateapplication',
            name='email',
            field=models.EmailField(default='nat@pfscerts.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesscertificateapplication',
            name='full_name',
            field=models.CharField(default='Nathaniel Amoafo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesscertificateapplication',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], default='Single', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesscertificateapplication',
            name='nationality',
            field=models.CharField(default='Ghanaian', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesscertificateapplication',
            name='occupation',
            field=models.CharField(default='Warehouse Manager', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesscertificateapplication',
            name='place_of_birth',
            field=models.CharField(default='Accra', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesscertificateapplication',
            name='type_of_business',
            field=models.CharField(choices=[('sole_proprietorship', 'Sole Proprietorship'), ('non_governmental_organization', 'Non-Governmental Organization'), ('limited_liability_company', 'Limited Liability Company')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesscertificateapplication',
            name='company_email',
            field=models.EmailField(max_length=100),
        ),
    ]
