# Generated by Django 5.2.1 on 2025-06-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_fdaapplication_custom_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscertificateapplication',
            name='custom_id',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='businesscertificateapplication',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10),
        ),
    ]
