# Generated by Django 5.2.1 on 2025-05-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_businesscertificateapplication_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscertificateapplication',
            name='contact_number_two',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
