# Generated by Django 5.2.1 on 2025-07-06 15:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_businesscertificateapplication_custom_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscertificateapplication',
            name='ghana_card_back',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='business_cert/gc/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesscertificateapplication',
            name='ghana_card_front',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='business_cert/gc/'),
            preserve_default=False,
        ),
    ]
