# Generated by Django 5.2.1 on 2025-07-06 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_businesscertificateapplication_ghana_card_back_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLCBusinessCertificateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=100)),
                ('place_of_birth', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('contact_number_one', models.CharField(max_length=15)),
                ('contact_number_two', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('custom_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('tin_number', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=10)),
                ('landmark', models.CharField(max_length=255)),
                ('street_name', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('gps_address', models.CharField(max_length=100)),
                ('postal_address', models.TextField()),
                ('business_name', models.CharField(max_length=100)),
                ('nature_of_business', models.CharField(max_length=100)),
                ('type_of_business', models.CharField(choices=[('non_governmental_organization', 'Non-Governmental Organization'), ('limited_liability_company', 'Limited Liability Company')], max_length=100)),
                ('business_postal_address', models.TextField()),
                ('business_contact_number_one', models.CharField(max_length=15)),
                ('business_contact_number_two', models.CharField(blank=True, max_length=15, null=True)),
                ('business_email', models.EmailField(max_length=100)),
                ('business_building_number', models.CharField(max_length=10)),
                ('business_landmark', models.CharField(max_length=255)),
                ('business_area', models.CharField(max_length=100)),
                ('business_district', models.CharField(max_length=100)),
                ('business_gps_address', models.CharField(max_length=100)),
                ('ghana_card_number', models.CharField(max_length=100)),
                ('ghana_card_front', models.ImageField(upload_to='business_cert/gc/')),
                ('ghana_card_back', models.ImageField(upload_to='business_cert/gc/')),
                ('business_tin_number', models.CharField(max_length=100)),
                ('application_status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('completed_documentation', 'Completed Documentation'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
