# Generated by Django 5.2.1 on 2025-05-15 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_businesscertificateapplication_application_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesscertificateapplication',
            old_name='company_name',
            new_name='business_name',
        ),
    ]
