# Generated by Django 5.2.1 on 2025-05-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_customuser_company_name_customuser_facebook_handle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile_photos/'),
        ),
    ]
