# Generated by Django 5.2.1 on 2025-05-16 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_customuser_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='company_name',
            new_name='business_name',
        ),
    ]
