# Generated by Django 5.2.1 on 2025-06-13 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('custom_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('type_of_product', models.CharField(max_length=200, verbose_name='Type of Product')),
                ('is_new_or_improvement', models.CharField(choices=[('new', 'New Product Idea'), ('improvement', 'Improvement of Existing Product')], max_length=20, verbose_name='Is this a New Idea or Improvement?')),
                ('goals', models.JSONField(default=list, verbose_name='What is/are your goal(s) for the Product?')),
                ('other_goal', models.CharField(blank=True, max_length=200, verbose_name='Other')),
                ('ingredient_or_dietary_notes', models.TextField(blank=True, verbose_name='Do you have a Preferred Ingredient List or any Dietary Restrictions?')),
                ('target_market', models.JSONField(default=list, verbose_name='Target Market')),
                ('other_target_market', models.CharField(blank=True, max_length=200, verbose_name='Other')),
                ('market_existence', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_sure', 'Not Sure')], max_length=20, verbose_name='Are there similar products already on the market?')),
                ('packaging_style', models.JSONField(default=list, verbose_name='What Packaging Style are you envisioning?')),
                ('custom_packaging', models.CharField(blank=True, max_length=200, verbose_name='Custom')),
                ('expected_launch_date', models.DateField(verbose_name='Expected Launch Date')),
                ('market_testing_feedback', models.CharField(choices=[('good', 'Yes, with good results'), ('need_more', 'Yes, but need more data'), ('not_yet', 'No, not yet'), ('planning', 'Planning to do so')], max_length=20, verbose_name='Have you done any Market Testing or Consumer Feedback?')),
                ('paid_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10)),
                ('application_status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('completed_documentation', 'Completed Documentation'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_development', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
