# Generated by Django 5.2.1 on 2025-06-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productintake',
            name='product_name',
            field=models.CharField(max_length=100, verbose_name='Product Name'),
        ),
    ]
