# Generated by Django 5.2.1 on 2025-06-16 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_productintake_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productintake',
            name='application_status',
        ),
        migrations.RemoveField(
            model_name='productintake',
            name='paid_status',
        ),
        migrations.RemoveField(
            model_name='productintake',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='productintake',
            name='updated_at',
        ),
    ]
