# Generated by Django 5.2.1 on 2025-06-16 14:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_productintake_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productintake',
            name='application_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('completed_documentation', 'Completed Documentation'), ('approved', 'Approved'), ('rejected', 'Rejected')], default=django.utils.timezone.now, max_length=30, verbose_name='Application Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productintake',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productintake',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productintake',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
