# Generated by Django 5.2.1 on 2025-07-06 10:56

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_productintake_application_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productintake',
            name='ingredient_or_dietary_notes',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Do you have a Preferred Ingredient List or any Dietary Restrictions?'),
        ),
    ]
